openapi: 3.0.0
info:
  title: 接口文档
  version: 1.0.0
paths:
  '/dawn/v1/api/goods/all/{limit}':
    get:
      tags:
        - 商品相关接口
      description: 获取所有商品
      operationId: 'app\modules\dawn\controllers\v1\api\GoodsController::actionAll'
      parameters:
        -
          name: page
          in: path
          description: 限度
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: '{''status'':0,''msg'':''OK'',''data'':{''list'':[{''id'':''2'',''name'':''测试商品6177'',''wholesale'':''421.30'',''sellingPrice'':''490.24'',''marketPrice'':''517.05'',''inventory'':1200,''updatedAt'':''2019-08-2114:05:54'',''operatedAt'':''2019-08-2114:05:54'',''status'':1},...],''limit'':5,''total'':78}}'
  '/dawn/v1/api/goods/list/{page}':
    get:
      tags:
        - 商品相关接口
      description: 获取商品列表
      operationId: 'app\modules\dawn\controllers\v1\api\GoodsController::actionIndex'
      parameters:
        -
          name: page
          in: path
          description: 页码数
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: '{''status'':0,''msg'':''OK'',''data'':{''list'':[{''id'':''2'',''name'':''测试商品6177'',''wholesale'':''421.30'',''sellingPrice'':''490.24'',''marketPrice'':''517.05'',''inventory'':1200,''updatedAt'':''2019-08-21 14:05:54'',''operatedAt'':''2019-08-21 14:05:54'',''status'':1},...],''page'':1,''total'':78,''pagesize'':10,''totalpages'':8}}'
  '/dawn/v1/api/goods/{id}':
    get:
      tags:
        - 商品相关接口
      description: 获取商品详情
      operationId: 'app\modules\dawn\controllers\v1\api\GoodsController::actionView'
      parameters:
        -
          name: id
          in: path
          description: 商品ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: '{''status'':0,''msg'':''OK'',''data'':{''id'':''2'',''name'':''测试商品6177'',''wholesale'':''421.30'',''sellingPrice'':''490.24'',''marketPrice'':''517.05'',inventory'':1200,''updatedAt'':''2019-08-21 14:05:54'',''operatedAt'':''2019-08-2114:05:54'',''status'':1}}'
    put:
      tags:
        - 商品相关接口
      description: 修改商品
      operationId: 'app\modules\dawn\controllers\v1\api\GoodsController::actionUpdate'
      responses:
        '200':
          description: ''
    delete:
      tags:
        - 商品相关接口
      description: 删除商品
      operationId: 'app\modules\dawn\controllers\v1\api\GoodsController::actionDelete'
      responses:
        '200':
          description: '{''status'':0,''msg'':''商品已删除'',''data'':[]}'
  /dawn/v1/api/goods:
    post:
      tags:
        - 商品相关接口
      description: 添加商品
      operationId: 'app\modules\dawn\controllers\v1\api\GoodsController::actionCreate'
      responses:
        '200':
          description: '{''status'':0,''msg''=>''OK'',''data'':{''id'':1}}'
  '/dawn/api/menu/list/{page}':
    get:
      tags:
        - 菜单相关接口
      operationId: 'app\modules\dawn\controllers\v1\api\MenuController::actionIndex'
      parameters:
        -
          name: page
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: ''
  '/dawn/api/menu/{id}':
    get:
      tags:
        - 菜单相关接口
      operationId: 'app\modules\dawn\controllers\v1\api\MenuController::actionView'
      parameters:
        -
          name: id
          in: path
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: ''
    put:
      tags:
        - 菜单相关接口
      operationId: 'app\modules\dawn\controllers\v1\api\MenuController::actionUpdate'
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
        -
          name: pid
          in: path
          required: false
          schema:
            type: integer
        -
          name: sn
          in: path
          required: false
          schema:
            type: string
        -
          name: name
          in: path
          required: false
          schema:
            type: string
        -
          name: url
          in: path
          required: false
          schema:
            type: string
        -
          name: sort
          in: path
          required: false
          schema:
            type: integer
        -
          name: icon
          in: path
          required: false
          schema:
            type: integer
        -
          name: status
          in: path
          required: false
          schema:
            type: integer
            enum:
              - 1
              - 2
      responses:
        '200':
          description: ''
    delete:
      tags:
        - 菜单相关接口
      operationId: 'app\modules\dawn\controllers\v1\api\MenuController::actionDelete'
      parameters:
        -
          name: id
          in: path
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: ''
  /dawn/api/menu:
    post:
      tags:
        - 菜单相关接口
      operationId: 'app\modules\dawn\controllers\v1\api\MenuController::actionCreate'
      parameters:
        -
          name: pid
          in: path
          required: false
          schema:
            type: integer
        -
          name: sn
          in: path
          required: false
          schema:
            type: string
        -
          name: name
          in: path
          required: false
          schema:
            type: string
        -
          name: url
          in: path
          required: false
          schema:
            type: string
        -
          name: sort
          in: path
          required: false
          schema:
            type: integer
        -
          name: icon
          in: path
          required: false
          schema:
            type: integer
        -
          name: status
          in: path
          required: false
          schema:
            type: integer
            enum:
              - 1
              - 2
      responses:
        '200':
          description: ''
  '/dawn/api/user/list/{page}':
    get:
      tags:
        - 用户相关接口
      operationId: 'app\modules\dawn\controllers\v1\api\UserController::actionIndex'
      parameters:
        -
          name: page
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: ''
  /dawn/api/user:
    post:
      tags:
        - 用户相关接口
      operationId: 'app\modules\dawn\controllers\v1\api\UserController::actionCreate'
      parameters:
        -
          name: user_name
          in: path
          description: 用户名
          required: true
          schema:
            type: string
        -
          name: real_name
          in: path
          description: 真实姓名
          required: false
          schema:
            type: string
        -
          name: gender
          in: path
          description: '0(女),1(男),2(未知)'
          required: false
          schema:
            type: integer
            enum:
              - 0
              - 1
              - 2
        -
          name: mobile_number
          in: path
          description: 手机号码
          required: true
          schema:
            type: mobile
      responses:
        '200':
          description: ''
